/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author user
 */
public class MenuMahasiswa extends javax.swing.JPanel {

    /**
     * Creates new form MenuMahasiswa
     */
    public MenuMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearchMhs = new javax.swing.JButton();
        btnViewMhs = new javax.swing.JButton();
        btnRemoveMhs = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddMhs = new javax.swing.JButton();

        btnSearchMhs.setText("Search Mahasiswa");
        btnSearchMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMhsActionPerformed(evt);
            }
        });

        btnViewMhs.setText("View Mahasiswa");

        btnRemoveMhs.setText("Remove Mahasiswa");
        btnRemoveMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMhsActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        jLabel1.setText("MAHASISWA");

        btnAddMhs.setText("Add Mahasiswa");
        btnAddMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMhsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnBack)
                        .addGap(50, 50, 50))
                    .addComponent(btnAddMhs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnRemoveMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearchMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnViewMhs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btnAddMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchMhsActionPerformed

    private void btnRemoveMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveMhsActionPerformed

    private void btnAddMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddMhsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMhs;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveMhs;
    private javax.swing.JButton btnSearchMhs;
    private javax.swing.JButton btnViewMhs;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public Object getBtnAddMhs(){
        return btnAddMhs;
    }
    
    public Object getBtnSearchMhs(){
        return btnSearchMhs;
    }
    
    public Object getBtnRemoveMhs(){
        return btnRemoveMhs;
    }
    
    public Object getBtnViewMhs(){
        return btnViewMhs;
    }
    
    public Object getBtnBack(){
        return btnBack;
    }
    
    public void addListener(ActionListener e){
        btnAddMhs.addActionListener(e);
        btnSearchMhs.addActionListener(e);
        btnRemoveMhs.addActionListener(e);
        btnViewMhs.addActionListener(e);
        btnBack.addActionListener(e);
    }
}
