/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author user
 */
public class MenuDosenKelas extends javax.swing.JPanel {

    /**
     * Creates new form MenuDosenKelas
     */
    public MenuDosenKelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewKelas = new javax.swing.JButton();
        btnRemoveKelas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSearchKelas = new javax.swing.JButton();
        btnCreateKelas = new javax.swing.JButton();

        btnViewKelas.setText("View Kelas");

        btnRemoveKelas.setText("Remove Kelas");
        btnRemoveKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveKelasActionPerformed(evt);
            }
        });

        jLabel1.setText("KELAS");

        btnBack.setText("Back");

        btnSearchKelas.setText("Search Kelas");
        btnSearchKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKelasActionPerformed(evt);
            }
        });

        btnCreateKelas.setText("Create Kelas");
        btnCreateKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnRemoveKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnViewKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnBack)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(btnCreateKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveKelasActionPerformed

    private void btnSearchKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchKelasActionPerformed

    private void btnCreateKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateKelasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateKelas;
    private javax.swing.JButton btnRemoveKelas;
    private javax.swing.JButton btnSearchKelas;
    private javax.swing.JButton btnViewKelas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
    public Object getBtnCreateKelas(){
        return btnCreateKelas;
    }
    
    public Object getBtnSearchKelas(){
        return btnSearchKelas;
    }
    
    public Object getBtnRemoveKelas(){
        return btnRemoveKelas;
    }
    
    public Object getBtnViewKelas(){
        return btnViewKelas;
    }
    
    public Object getBtnBack(){
        return btnBack;
    }
    
    public void addListener(ActionListener e){
        btnCreateKelas.addActionListener(e);
        btnSearchKelas.addActionListener(e);
        btnRemoveKelas.addActionListener(e);
        btnViewKelas.addActionListener(e);
        btnBack.addActionListener(e);
    }
}
